**Examen 2 Analitica y Ciencia de Datos**

**Rementeria Medina Jesus Hector 20170791**

In [30]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

**1: Cargue en un Dataframe los datos de los accidentes de los últimos 3 años*

In [31]:

df2020 = pd.read_csv("../input/atus_anual_2020.csv", index_col=False)
df2021 = pd.read_csv("../input/atus_anual_2021.csv", index_col=False)
df2022 = pd.read_csv("../input/atus_anual_2022.csv", index_col=False)
dfAccidentes = pd.concat([df2020, df2021, df2022])
dfAccidentes

,COBERTURA,ID_ENTIDAD,ID_MUNICIPIO,ANIO,MES,ID_HORA,ID_MINUTO,ID_DIA,DIASEMANA,URBANA,...,PEATMUERTO,PEATHERIDO,CICLMUERTO,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,CLASACC,ESTATUS
0,Municipal,1,1,2020,1,0,0,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
1,Municipal,1,1,2020,1,0,0,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
2,Municipal,1,1,2020,1,0,10,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
3,Municipal,1,1,2020,1,2,0,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
4,Municipal,1,1,2020,1,2,10,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95780,Municipal,11,3,2022,7,15,41,5,Martes,Sin accidente en esta zona,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
95781,Municipal,11,3,2022,7,18,0,5,Martes,Accidente en no intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
95782,Municipal,11,3,2022,7,17,52,6,Miercoles,Accidente en no intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
95783,Municipal,11,3,2022,7,0,55,7,Jueves,Accidente en no intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
95784,Municipal,11,3,2022,7,14,16,7,Jueves,Accidente en inter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
dfAccidentes = dfAccidentes.reset_index(drop=True)
dfAccidentes

,COBERTURA,ID_ENTIDAD,ID_MUNICIPIO,ANIO,MES,ID_HORA,ID_MINUTO,ID_DIA,DIASEMANA,URBANA,...,PEATMUERTO,PEATHERIDO,CICLMUERTO,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,CLASACC,ESTATUS
0,Municipal,1,1,2020,1,0,0,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
1,Municipal,1,1,2020,1,0,0,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
2,Municipal,1,1,2020,1,0,10,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
3,Municipal,1,1,2020,1,2,0,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
4,Municipal,1,1,2020,1,2,10,1,Miercoles,Accidente en intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502344,Municipal,11,3,2022,7,15,41,5,Martes,Sin accidente en esta zona,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
502345,Municipal,11,3,2022,7,18,0,5,Martes,Accidente en no intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
502346,Municipal,11,3,2022,7,17,52,6,Miercoles,Accidente en no intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
502347,Municipal,11,3,2022,7,0,55,7,Jueves,Accidente en no intersección,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas
502348,Municipal,11,3,2022,7,14,16,7,Jueves,Accidente en inter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Verificar las Columnas

In [33]:
dfAccidentes.columns

Index(['COBERTURA', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'ANIO', 'MES', 'ID_HORA',
       'ID_MINUTO', 'ID_DIA', 'DIASEMANA', 'URBANA', 'SUBURBANA', 'TIPACCID',
       'AUTOMOVIL', 'CAMPASAJ', 'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA',
       'CAMIONETA', 'CAMION', 'TRACTOR', 'FERROCARRI', 'MOTOCICLET',
       'BICICLETA', 'OTROVEHIC', 'CAUSAACCI', 'CAPAROD', 'SEXO', 'ALIENTO',
       'CINTURON', 'ID_EDAD', 'CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO',
       'PASAHERIDO', 'PEATMUERTO', 'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO',
       'OTROMUERTO', 'OTROHERIDO', 'NEMUERTO', 'NEHERIDO', 'CLASACC',
       'ESTATUS'],
      dtype='object')

**2: Agregue una columna tipo date que englobe las columnas correspondientes a Año, Mes, Dia, Hora y Minuto**

In [34]:
dfAccidentes['FECHA'] = pd.to_datetime({'year': dfAccidentes["ANIO"],
                                       'month': dfAccidentes["MES"],
                                       'day': dfAccidentes["ID_DIA"],
                                       'hours': dfAccidentes["ID_HORA"],
                                       'minutes': dfAccidentes["ID_MINUTO"]})
dfAccidentes['FECHA']

0        2020-01-01 00:00:00
1        2020-01-01 00:00:00
2        2020-01-01 00:10:00
3        2020-01-01 02:00:00
4        2020-01-01 02:10:00
                 ...
502344   2022-07-05 15:41:00
502345   2022-07-05 18:00:00
502346   2022-07-06 17:52:00
502347   2022-07-07 00:55:00
502348   2022-07-07 14:16:00
Name: FECHA, Length: 502349, dtype: datetime64[ns]

**3: Agregue una columna para Área cuyos valores serán Urbana o Suburbana dependiendo del área donde ocurrió el accidente**


**Funcion fill_area**

In [35]:
def fill_area(row):
    if 'Sin accidente en esta zona' not in row["URBANA"]:
        return 'Urbana'
    elif 'Sin accidente en esta zona' not in row["SUBURBANA"]:
        return 'Suburbana'
    else:
        return 'NA'
print("Se ejecutó correctamente")

Se ejecutó correctamente

Aplicar fill_area a la nueva columna

In [36]:
dfAccidentes['AREA'] = dfAccidentes.apply(lambda dato: fill_area(dato), axis=1)
print(dfAccidentes['AREA'])

0            Urbana
1            Urbana
2            Urbana
3            Urbana
4            Urbana
            ...
502344    Suburbana
502345       Urbana
502346       Urbana
502347       Urbana
502348       Urbana
Name: AREA, Length: 502349, dtype: object

**4: Agregue una columna Zona cuyos valores serán la zona donde ocurrió el accidente**

In [37]:
def fill_zone(row):
    if 'Sin accidente en esta zona' not in row['URBANA']:
        return row['URBANA']
    elif 'Sin accidente en esta zona' not in row['SUBURBANA']:
        return row['SUBURBANA']
    else:
        return 'NA'
print("Se ejecutó correctamente")

Se ejecutó correctamente

Aplicar la función fill_zone' a la nueva columna

In [38]:
dfAccidentes['ZONA'] = dfAccidentes.apply(fill_zone, axis=1)
print(dfAccidentes['ZONA'])

0              Accidente en intersección
1              Accidente en intersección
2              Accidente en intersección
3              Accidente en intersección
4              Accidente en intersección
                       ...
502344    Accidente en carretera estatal
502345      Accidente en no intersección
502346      Accidente en no intersección
502347      Accidente en no intersección
502348                Accidente en inter
Name: ZONA, Length: 502349, dtype: object

**5: Elimine las columnas URBANA y SUBURBANA**

In [39]:
dfAccidentes = dfAccidentes.drop(['URBANA', 'SUBURBANA'], axis=1)
dfAccidentes

,COBERTURA,ID_ENTIDAD,ID_MUNICIPIO,ANIO,MES,ID_HORA,ID_MINUTO,ID_DIA,DIASEMANA,TIPACCID,...,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,CLASACC,ESTATUS,FECHA,AREA,ZONA
0,Municipal,1,1,2020,1,0,0,1,Miercoles,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2020-01-01 00:00:00,Urbana,Accidente en intersección
1,Municipal,1,1,2020,1,0,0,1,Miercoles,Colisión con objeto fijo,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2020-01-01 00:00:00,Urbana,Accidente en intersección
2,Municipal,1,1,2020,1,0,10,1,Miercoles,Colisión con motocicleta,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2020-01-01 00:10:00,Urbana,Accidente en intersección
3,Municipal,1,1,2020,1,2,0,1,Miercoles,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2020-01-01 02:00:00,Urbana,Accidente en intersección
4,Municipal,1,1,2020,1,2,10,1,Miercoles,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2020-01-01 02:10:00,Urbana,Accidente en intersección
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502344,Municipal,11,3,2022,7,15,41,5,Martes,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2022-07-05 15:41:00,Suburbana,Accidente en carretera estatal
502345,Municipal,11,3,2022,7,18,0,5,Martes,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2022-07-05 18:00:00,Urbana,Accidente en no intersección
502346,Municipal,11,3,2022,7,17,52,6,Miercoles,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2022-07-06 17:52:00,Urbana,Accidente en no intersección
502347,Municipal,11,3,2022,7,0,55,7,Jueves,Colisión con vehículo automotor,...,0.0,0.0,0.0,0.0,0.0,Sólo daños,Cifras Definitivas,2022-07-07 00:55:00,Urbana,Accidente en no intersección
502348,Municipal,11,3,2022,7,14,16,7,Jueves,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-07 14:16:00,Urbana,Accidente en inter

Verificar que se elimino

In [40]:
dfAccidentes.columns

Index(['COBERTURA', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'ANIO', 'MES', 'ID_HORA',
       'ID_MINUTO', 'ID_DIA', 'DIASEMANA', 'TIPACCID', 'AUTOMOVIL', 'CAMPASAJ',
       'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA', 'CAMIONETA', 'CAMION',
       'TRACTOR', 'FERROCARRI', 'MOTOCICLET', 'BICICLETA', 'OTROVEHIC',
       'CAUSAACCI', 'CAPAROD', 'SEXO', 'ALIENTO', 'CINTURON', 'ID_EDAD',
       'CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO', 'PASAHERIDO', 'PEATMUERTO',
       'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO', 'OTROMUERTO', 'OTROHERIDO',
       'NEMUERTO', 'NEHERIDO', 'CLASACC', 'ESTATUS', 'FECHA', 'AREA', 'ZONA'],
      dtype='object')

**6: Determine cual municipio de cada estado tuvo más meses sin accidentes**

In [41]:
accidentes_mes = dfAccidentes.groupby(["ID_ENTIDAD", "ID_MUNICIPIO", "MES"])["MES"].count().rename('ACCIDENTES')
accidentes_mes = accidentes_mes.reset_index()
accidentes_mes

       ID_ENTIDAD  ID_MUNICIPIO  MES  ACCIDENTES
0               1             1    1         770
1               1             1    2         755
2               1             1    3         834
3               1             1    4         795
4               1             1    5         863
...           ...           ...  ...         ...
21382          26             4    2           2
21383          26             4    3           7
21384          26             4    4           9
21385          26             4    5           5
21386          26             4    6           6

[21387 rows x 4 columns]


Meses sin accidentes

In [42]:
accidentes_mes.groupby(["ID_ENTIDAD", "ID_MUNICIPIO"])["MES"].count().reset_index(name='MESES_SIN_ACCIDENTES')

      ID_ENTIDAD  ID_MUNICIPIO  MESES_SIN_ACCIDENTES
0              1             1                    12
1              1             2                    12
2              1             3                    12
3              1             4                    12
4              1             5                    12
...          ...           ...                   ...
1833          25            18                    12
1834          26             1                    12
1835          26             2                    12
1836          26             3                    12
1837          26             4                     6

[1838 rows x 3 columns]

Resultado:

In [43]:
meses_sinaccidentes = accidentes_mes[accidentes_mes["ACCIDENTES"] == 0]
meses_sinaccidentes

Empty DataFrame
Columns: [ID_ENTIDAD, ID_MUNICIPIO, MES, ACCIDENTES]
Index: []

Separado por año

In [44]:
accidentes_mes2 = dfAccidentes.groupby(["ID_ENTIDAD", "ID_MUNICIPIO", "ANIO", "MES"])["MES"].count().reset_index(name='ACCIDENTES')
accidentes_mes2

       ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ACCIDENTES
0               1             1  2020    1         267
1               1             1  2020    2         253
2               1             1  2020    3         295
3               1             1  2020    4         220
4               1             1  2020    5         235
...           ...           ...   ...  ...         ...
32372          26             4  2020    2           2
32373          26             4  2020    3           7
32374          26             4  2020    4           9
32375          26             4  2020    5           5
32376          26             4  2020    6           6

[32377 rows x 5 columns]

No hubo ningun mes en el que no ocurriera por lo menos un accidente

In [45]:
meses_sinaccidentes2 = accidentes_mes2[accidentes_mes2["ACCIDENTES"] == 0]
meses_sinaccidentes2

Empty DataFrame
Columns: [ID_ENTIDAD, ID_MUNICIPIO, ANIO, MES, ACCIDENTES]
Index: []

**7: Resuma los accidentes del último año por tipo y que porcentaje representan**

In [46]:
accidentes_2022 = dfAccidentes[dfAccidentes["ANIO"] == 2022]
accidentes_2022.groupby("TIPACCID")["TIPACCID"].agg(['count'])

                                       count
TIPACCID
Caída de pasajero                        472
Certificado cero                        1502
Colisión con animal                      282
Colisión con ciclista                   1167
Colisión con ferrocarril                  77
Colisión con motocicleta               11718
Colisión con objeto fijo               11611
Colisión con peatón (atropellamiento)   3508
Colisión con vehículo automotor        60405
Incendio                                  29
Otro                                     943
Salida del camino                       1833
Volcadura                               2237

In [47]:
total = len(accidentes_2022) #total
conteo_accidentes = accidentes_2022["TIPACCID"].value_counts() #clasificado por tipo
conteo_accidentes

TIPACCID
Colisión con vehículo automotor          60405
Colisión con motocicleta                 11718
Colisión con objeto fijo                 11611
Colisión con peatón (atropellamiento)     3508
Volcadura                                 2237
Salida del camino                         1833
Certificado cero                          1502
Colisión con ciclista                     1167
Otro                                       943
Caída de pasajero                          472
Colisión con animal                        282
Colisión con ferrocarril                    77
Incendio                                    29
Name: count, dtype: int64

In [48]:
porcentaje_accidentes = (conteo_accidentes / total)*100
porcentaje_accidentes

TIPACCID
Colisión con vehículo automotor          63.063110
Colisión con motocicleta                 12.233648
Colisión con objeto fijo                 12.121940
Colisión con peatón (atropellamiento)     3.662369
Volcadura                                 2.335439
Salida del camino                         1.913661
Certificado cero                          1.568095
Colisión con ciclista                     1.218354
Otro                                      0.984497
Caída de pasajero                         0.492770
Colisión con animal                       0.294409
Colisión con ferrocarril                  0.080388
Incendio                                  0.030276
Name: count, dtype: float64


Se puede ver el porcentaje de cada tipo de accidente y se llega a la conclusion que el mas frecuente
fue la colision con otro vehiculo y el menos frecuente fue la colision con forrecarriles

In [49]:
dfporcentajes = pd.DataFrame({'TIPO_ACCIDENTE': conteo_accidentes.index,
                             'CONTEO': conteo_accidentes.values,
                             'PORCENTAJE': porcentaje_accidentes.values})
dfporcentajes

                           TIPO_ACCIDENTE  CONTEO  PORCENTAJE
0         Colisión con vehículo automotor   60405   63.063110
1                Colisión con motocicleta   11718   12.233648
2                Colisión con objeto fijo   11611   12.121940
3   Colisión con peatón (atropellamiento)    3508    3.662369
4                               Volcadura    2237    2.335439
5                       Salida del camino    1833    1.913661
6                        Certificado cero    1502    1.568095
7                   Colisión con ciclista    1167    1.218354
8                                    Otro     943    0.984497
9                       Caída de pasajero     472    0.492770
10                    Colisión con animal     282    0.294409
11               Colisión con ferrocarril      77    0.080388
12                               Incendio      29    0.030276

**8: Obtenga la cantidad de muertos y lesionados de los últimos 3 años**

In [50]:
dfAccidentes.columns

Index(['COBERTURA', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'ANIO', 'MES', 'ID_HORA',
       'ID_MINUTO', 'ID_DIA', 'DIASEMANA', 'TIPACCID', 'AUTOMOVIL', 'CAMPASAJ',
       'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA', 'CAMIONETA', 'CAMION',
       'TRACTOR', 'FERROCARRI', 'MOTOCICLET', 'BICICLETA', 'OTROVEHIC',
       'CAUSAACCI', 'CAPAROD', 'SEXO', 'ALIENTO', 'CINTURON', 'ID_EDAD',
       'CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO', 'PASAHERIDO', 'PEATMUERTO',
       'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO', 'OTROMUERTO', 'OTROHERIDO',
       'NEMUERTO', 'NEHERIDO', 'CLASACC', 'ESTATUS', 'FECHA', 'AREA', 'ZONA'],
      dtype='object')

se comprueba que cuente con valores diferentes de 0

In [51]:
muertos = (dfAccidentes["CONDMUERTO"]+dfAccidentes["PASAMUERTO"]+dfAccidentes["PEATMUERTO"]+dfAccidentes["CICLMUERTO"]+dfAccidentes["OTROMUERTO"]+dfAccidentes["NEMUERTO"]).reset_index(name='MUERTOS')
muertos

         index  MUERTOS
0            0      0.0
1            1      0.0
2            2      0.0
3            3      0.0
4            4      0.0
...        ...      ...
502344  502344      0.0
502345  502345      0.0
502346  502346      0.0
502347  502347      0.0
502348  502348      NaN

[502349 rows x 2 columns]

In [52]:
lesionados = (dfAccidentes["CONDHERIDO"]+dfAccidentes["PASAHERIDO"]+dfAccidentes["PEATHERIDO"]+dfAccidentes["CICLHERIDO"]+dfAccidentes["OTROHERIDO"]+dfAccidentes["NEHERIDO"]).reset_index(name='LESIONADOS')
lesionados

         index  LESIONADOS
0            0         0.0
1            1         0.0
2            2         0.0
3            3         0.0
4            4         0.0
...        ...         ...
502344  502344         0.0
502345  502345         0.0
502346  502346         0.0
502347  502347         0.0
502348  502348         NaN

[502349 rows x 2 columns]

Se crea la informacion en un nuevo def

In [53]:
dfAccidentados = pd.DataFrame({'AÑO': dfAccidentes["ANIO"],
                              'MUERTOS': dfAccidentes["CONDMUERTO"]+dfAccidentes["PASAMUERTO"]+dfAccidentes["PEATMUERTO"]+dfAccidentes["CICLMUERTO"]+dfAccidentes["OTROMUERTO"]+dfAccidentes["NEMUERTO"],
                              'LESIONADOS': dfAccidentes["CONDHERIDO"]+dfAccidentes["PASAHERIDO"]+dfAccidentes["PEATHERIDO"]+dfAccidentes["CICLHERIDO"]+dfAccidentes["OTROHERIDO"]+dfAccidentes["NEHERIDO"]})
dfAccidentados

         AÑO  MUERTOS  LESIONADOS
0       2020      0.0         0.0
1       2020      0.0         0.0
2       2020      0.0         0.0
3       2020      0.0         0.0
4       2020      0.0         0.0
...      ...      ...         ...
502344  2022      0.0         0.0
502345  2022      0.0         0.0
502346  2022      0.0         0.0
502347  2022      0.0         0.0
502348  2022      NaN         NaN

[502349 rows x 3 columns]

In [54]:
años_muertos_lesionados = dfAccidentados.groupby("AÑO").agg({"MUERTOS": 'sum', "LESIONADOS": 'sum'})
años_muertos_lesionados

      MUERTOS  LESIONADOS
AÑO
2020   3181.0     58717.0
2021   1829.0     37594.0
2022   1235.0     27699.0

In [55]:
muertos_lesionados = dfAccidentados.agg({"MUERTOS": 'sum', "LESIONADOS": 'sum'}).reset_index()
muertos_lesionados

        index         0
0     MUERTOS    6245.0
1  LESIONADOS  124010.0

**9: ¿Cómo se compara el número de accidentes de cada año contra el anterior? ¿En qué porcentaje varió?**

In [56]:
año_2020 = len(df2020)
año_2021 = len(df2021)
año_2022 = len(df2022)

accidentes_año = dfAccidentes["ANIO"].value_counts().reset_index(name='ACCIDENTES')
accidentes_año

   ANIO  ACCIDENTES
0  2020      269666
1  2021      136898
2  2022       95785

Funcion para obtener el procentaje de variación

In [57]:
def variation(row):
    if row.name < len(accidentes_año) - 1:
        año_act = row["ACCIDENTES"]
        año_ant = accidentes_año.at[row.name + 1, "ACCIDENTES"]
        variation = ((año_act-año_ant)/año_ant)*100
        return variation
    else: 
        return None

print("Terminó de ejecutarse")

Terminó de ejecutarse


Se puede ver que el porcentaje de variacion entre un año y otro es positivo con un aproximado del 10% de diferencia,
en los años mas antiguos el crecimiento es mayor por lo que puede deducirse que el crecimiento disminuye con el tiempo

In [58]:
accidentes_año['VARIACION'] = accidentes_año.apply(variation, axis=1)
accidentes_año

   ANIO  ACCIDENTES  VARIACION
0  2020      269666  96.983155
1  2021      136898  42.922169
2  2022       95785        NaN